  version: '3'
  services:
    redis:
        image: redis:alpine
        container_name: redis-server-chat
        ports:
          - "6380:6379"
        command: redis-server --requirepass mysecretpassword
